import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'te' | 'ta';

const translations = {
    en: {
        // UI: GENERAL & APP
        app_title: "KrishiNiti", credit_score: "Credit Score", season: "Season", start_season: "Start New Season", goals: "Life Goals", bank: "Bank & Gold", schemes: "Govt Schemes", shop: "Asset Shop", reports: "Reports", profile: "My Profile", quit: "Quit & Restart", confirm_quit: "Are you sure you want to quit and start a new game?", advisory: "Krishi Mitra Advisory", ui_back: "Back", ui_continue: "Continue", ui_confirm: "Confirm", splash_subtitle: "Farming & Finance Game", unknown_phase: "Unknown Phase", ui_switch_lang: "Switch Language", ui_restart_game: "Restart Game", header_savings: "Savings", header_debt: "Debt", header_wellbeing: "Wellbeing",

        // UI: SETUP & GOALS
        setup_title: "Your Farm", setup_subtitle: "Set up your farm profile", setup_land_size: "Land Size", setup_farm_type: "Farming Type", goal_sel_title: "What is your Dream?", goal_sel_subtitle: "Financial literacy helps you achieve life goals.", goal_target: "Target:", goal_main_badge: "Main Dream", goals_avail_savings: "Available Savings", goals_pay_achieve: "Pay & Achieve Goal", goals_need_more: "Need ₹{val} more", goals_completed: "Goal Completed!",

        // UI: BANK
        bank_title: "Gramin Bank", bank_avail_bal: "Available Balance", bank_land_loan: "Land Loan", bank_principal_left: "Principal Left:", bank_season_emi: "Season EMI:", bank_repay_prin: "Repay Principal", bank_pay_btn: "Pay", bank_fd: "Fixed Deposit", bank_fd_return: "10% Return", bank_locked: "Locked:", bank_matures: "Matures Season", bank_invest_btn: "Invest", bank_gold: "Digital Gold", bank_gold_held: "Gold Held:", bank_rate: "Rate:", bank_grams: "Grams", bank_buy_btn: "Buy", bank_sell_btn: "Sell",

        // UI: EVENTS, MARKET & HARVEST
        ui_scanning: "Scanning Fields...", ui_stage: "Stage", ui_of: "of", ui_what_do: "What will you do?", ui_free: "Free", ui_harvest_ready: "Harvest Ready!", ui_where_sell: "Where do you want to sell your {val}?", ui_total_land: "Total Land:", ui_acres: "Acres", ui_base_price: "Current Base Price:", ui_per_unit: "/ unit", ui_yield_warning: "Due to events, your yield is lower. Watch your transport costs!", ui_select_mandi: "Select Market (Mandi)", ui_est_gross: "Est. Gross Income", ui_transport_cost: "Total Transport Cost", ui_est_net: "Est. Net Revenue", ui_sell_here: "Sell Here", ui_harvest_report: "Harvest Report", ui_season_results: "Season {val} Results", ui_net_profit: "Net Profit", ui_crop_sales: "Crop Sales Income", ui_insurance_payout: "Insurance Payout", ui_total_expenses: "Total Expenses", ui_sold_at: "Sold at:", ui_new_savings: "New Savings", ui_current_debt: "Current Debt", ui_outstanding_debt: "Outstanding Debt:", ui_repay_warning: "Repayment affects your Credit Score.", ui_pay_full: "Pay Full Amount", ui_score_plus_50: "(+50 Score)", ui_pay_interest: "Pay Interest Only", ui_score_minus_10: "(-10 Score)", ui_defer_pay: "Defer Payment (Risk Default)", ui_check_resilience: "Check Resilience Score",

        // UI: PROFILE, REPORTS, ALERTS
        profile_farmer: "Farmer", profile_resilience: "Resilience", profile_owned_assets: "Owned Assets", profile_no_assets: "No assets purchased yet. Visit the shop!", reports_empty: "No harvest history yet.", resil_title: "Financial Resilience", resil_index: "Index", resil_savings: "Savings Discipline", resil_risk: "Risk Preparedness", resil_debt: "Debt Stability", resil_improve: "Needs improvement", resil_excellent: "Excellent!", resil_good: "Good, keep going", resil_next_season: "Start Next Season", vis_field_ready: "Field Ready for Sowing", shop_buy_land_confirm: "Buy 1 Acre? Down Payment: ₹{down}. Remaining ₹{loan} will be a loan.", plan_insufficient_funds: "Insufficient Funds! You need ₹{cost} for {acres} acres.", goals_confirm_purchase: "Spend ₹{cost} to achieve {name}?",

        // DATA: CROPS, ASSETS, LOANS, GOALS, MANDIS
        crop_wheat: "Wheat", crop_cotton: "Cotton", crop_soybean: "Soybean", crop_onion: "Onion", crop_tomato: "Tomato", type_crop: "CROP", type_veg: "VEGETABLE", type_mixed: "MIXED",
        loan_kcc: "Kisan Credit Card", loan_coop: "Co-operative Society", loan_sahukar: "Local Moneylender", ins_none: "No Insurance", ins_pmfby: "PMFBY Insurance",
        asset_type_infra: "INFRASTRUCTURE", asset_type_machinery: "MACHINERY", asset_drip: "Drip Irrigation", asset_drip_desc: "Saves water. Protects yield during Droughts.", asset_tractor: "Power Tiller", asset_tractor_desc: "Good for small fields. Reduces labor cost.", asset_greenhouse: "Polyhouse Net", asset_greenhouse_desc: "Protects vegetables from pests.", asset_solar: "Solar Water Pump", asset_solar_desc: "Free electricity for irrigation.", asset_warehouse: "Small Godown", asset_warehouse_desc: "Store crops safely to avoid selling at a loss.",
        goal_tractor: "Heavy Duty Tractor", goal_tractor_desc: "A 45HP Tractor for large scale farming.", goal_edu: "Children's Higher Ed", goal_edu_desc: "Engineering or Medical college fees.", goal_land: "Buy Neighbor's Field", goal_land_desc: "Expand your farm by 5 acres.", goal_house: "Build Pucca House", goal_house_desc: "A concrete house to protect your family.", goal_wedding: "Grand Wedding", goal_wedding_desc: "A respectable wedding ceremony.",
        mandi_local: "Local Village APMC", mandi_local_desc: "Sell immediately in your village. Zero transport costs.", mandi_district: "District Main Mandi", mandi_district_desc: "Rent a small truck. Good balance of price and cost.", mandi_state: "State Agricultural Market", mandi_state_desc: "Hire heavy transport. Highest prices, high fees.",

        // DATA: SCHEMES
        sch_info: "Applying for government schemes is free. They provide crucial financial safety nets.", sch_eligibility: "Eligibility", sch_benefit: "Benefit", sch_enrolled: "Enrolled & Active", sch_apply: "Apply Now", sch_not_eligible: "Not Eligible", sch_all_e: "All farmers are eligible.",
        sch_pmkisan_n: "PM-KISAN Yojana", sch_pmkisan_d: "Direct Benefit Transfer (DBT) providing income support to farmers.", sch_pmkisan_b: "Receives ₹2,000 per season directly into bank account.", sch_pmkisan_e: "Must own 5 acres or less of land.",
        sch_pmfby_n: "PMFBY Crop Insurance", sch_pmfby_d: "Pradhan Mantri Fasal Bima Yojana protects against natural calamities.", sch_pmfby_b: "Reduces PMFBY crop insurance premiums by 50%.",
        sch_miss_n: "MISS (Interest Subvention)", sch_miss_d: "Modified Interest Subvention Scheme for short-term agricultural loans.", sch_miss_b: "Reduces KCC Loan interest rate from 7% to 4%.", sch_miss_e: "Requires Credit Score of 600+.",
        sch_soil_n: "Soil Health Card", sch_soil_d: "Provides crop-wise recommendations of nutrients and fertilizers required.", sch_soil_b: "Reduces seasonal crop input costs by 10%.",
        sch_enam_n: "e-NAM Portal", sch_enam_d: "National Agriculture Market connects farmers to nationwide buyers digitally.", sch_enam_b: "Increases final crop selling price by 10%.",
        sch_kusum_n: "PM-KUSUM Subsidy", sch_kusum_d: "Government subsidy scheme for solar-powered irrigation.", sch_kusum_b: "50% Off capital cost when buying a Solar Water Pump.",
        sch_drop_n: "Per Drop More Crop", sch_drop_d: "Promotes micro-irrigation technologies to ensure water efficiency.", sch_drop_b: "50% Off capital cost when buying Drip Irrigation.",
        sch_smam_n: "SMAM (Mechanization)", sch_smam_d: "Sub-Mission on Agricultural Mechanization to make machinery affordable.", sch_smam_b: "50% Off capital cost when buying a Mini Tractor.",

        // DATA: EVENTS
        evt_fraud_title: "OTP Scam Call", evt_fraud_desc: "Caller claims to be bank manager asking for OTP.", evt_fraud_a: "Cut Call & Block", evt_fraud_b: "Share OTP",
        evt_seeds_title: "Poor Germination", evt_seeds_desc: "Seeds are not sprouting well.", evt_seeds_a: "Re-sow Field", evt_seeds_b: "Wait it out",
        evt_monsoon_title: "Monsoon Delayed", evt_monsoon_desc: "Rains are late. Soil is drying up.", evt_monsoon_a: "Rent Water Tanker", evt_monsoon_b: "Hope for rain",
        evt_theft_title: "Cash Risk", evt_theft_desc: "Carrying large cash for fertilizer is risky.", evt_theft_a: "Pay via UPI", evt_theft_b: "Pay Cash",
        evt_pest_title: "Pest Attack", evt_pest_desc: "Bollworms are damaging the crop.", evt_pest_a: "Spray Pesticide", evt_pest_b: "Home Remedy",
        evt_motor_title: "Motor Burnt", evt_motor_desc: "Irrigation motor burnt due to voltage spike.", evt_motor_a: "Repair Immediately", evt_motor_b: "Skip Irrigation",
        evt_mandi_title: "Trader vs Mandi", evt_mandi_desc: "Local trader offers instant cash but lower rates.", evt_mandi_a: "Sell at Mandi (UPI)", evt_mandi_b: "Sell to Trader",
        evt_hail_title: "Hailstorm", evt_hail_desc: "Heavy hail just before harvest!", evt_hail_a: "Emergency Harvest", evt_hail_b: "Do nothing",
        evt_crash_title: "Price Crash", evt_crash_desc: "Market prices dropped by 40% due to glut.", evt_crash_a: "Use Cold Storage", evt_crash_b: "Sell at low price",

        // DATA: SUMMARY PERSONAS
        sum_complete: "Simulation Complete", sum_identity: "Your Financial Identity", sum_report: "Final Report Card", sum_networth: "Total Net Worth", sum_land: "Land Owned", sum_goals: "Goals Achieved", sum_final_debt: "Final Debt", sum_restart: "Start New Journey",
        per_debt_t: "The Debt Walker", per_debt_d: "You survived, but left with ₹{val} in debt. High interest loans ate your future. Next time, use the Bank to save for emergencies.",
        per_ratna_t: "The Krishi Ratna", per_ratna_d: "Master of farming! You achieved your Life Dream AND built a massive fortune. You are an inspiration to the village.",
        per_dream_t: "The Dream Chaser", per_dream_d: "Congratulations! You focused on what matters and achieved your dream: {val}. You are financially free.",
        per_zamin_t: "The Zamindar", per_zamin_d: "You grew your farm to {val} Acres! You believe land is the only real wealth. You are the largest landowner in the region.",
        per_invest_t: "The Savvy Investor", per_invest_d: "You accumulated great wealth through crops and banking, but you forgot to buy your main Life Goal. You are rich, but are you happy?",
        per_bank_t: "The Bank's Favorite", per_bank_d: "You have an impeccable Credit Score (800+). You played it very safe. Next time, take some calculated risks to grow faster.",
        per_survive_t: "The Survivor", per_survive_d: "You made it through {val} seasons. You survived the storms and pests, but just barely. Try planning your seeds and loans better next time.",

        // DATA: ADVISOR & QUIZZES
        adv_urgent_debt: "⚠️ Urgent: Your debt is dangerously high. Repay loans before expanding!", adv_poverty_spiral: "🚨 Warning: You are in a debt trap! Seek Bank loans, avoid Moneylenders.", adv_use_score: "💡 Prioritize getting the 4% KCC loan over expensive alternatives.", adv_pm_kisan: "💡 Tip: Visit Govt Schemes to claim your ₹2,000 PM-KISAN.", adv_fd_idle: "📈 Tip: You have ₹{val} sitting idle. Put it in a Fixed Deposit!", adv_soil_health: "🌱 Tip: Apply for Soil Health Card to reduce fertilizer costs by 10%.", adv_pmfby: "🛡️ Tip: Enroll in PMFBY to get 50% subsidy on crop insurance.", adv_improve_credit: "🏦 Tip: Repay loans to improve Credit Score.", adv_solar_kusum: "☀️ Tip: Apply for PM-KUSUM first to get 50% off Solar Pumps!", adv_expand_land: "🚜 Tip: You have enough for a down payment on new land.", adv_buy_gold: "🪙 Tip: Diversify your wealth! Buy Digital Gold.", adv_gen_moneylender: "Remember: A moneylender's 36% interest rate leads to a debt trap.", adv_gen_diversify: "Crop diversification is natural insurance against weather.", adv_gen_drip: "Drip Irrigation reduces vulnerability to droughts.", adv_gen_transport: "Check market transport costs before selling.", adv_gen_praise: "🌟 Excellent work! Your farm is financially healthy.",
        quiz_kcc_q: "What is the primary benefit of the Kisan Credit Card (KCC)?", quiz_kcc_o1: "Free tractor subsidies", quiz_kcc_o2: "Low-interest farming loans", quiz_kcc_o3: "Free weather updates", quiz_kcc_o4: "Guaranteed market prices", quiz_kcc_exp: "KCC provides farmers with timely and adequate credit at very low interest rates compared to moneylenders.",
        quiz_pmfby_q: "What does the PMFBY scheme protect you against?", quiz_pmfby_o1: "Theft of farm equipment", quiz_pmfby_o2: "Crop loss due to natural calamities", quiz_pmfby_o3: "Medical emergencies", quiz_pmfby_o4: "Market price drops", quiz_pmfby_exp: "PMFBY is the government's flagship crop insurance scheme that financially protects farmers if crops are destroyed by weather.",
        quiz_compound_q: "Why is a local Moneylender's 36% interest rate extremely dangerous?", quiz_compound_o1: "They require too much paperwork", quiz_compound_o2: "Debt grows exponentially faster", quiz_compound_o3: "They give loans in cash only", quiz_compound_o4: "There is no difference from a bank", quiz_compound_exp: "High-interest loans compound rapidly, trapping farmers in permanent debt.",
        quiz_div_q: "What is 'Crop Diversification' in financial terms?", quiz_div_o1: "Planting only one high-value crop every year", quiz_div_o2: "Growing different types of crops to spread out risk", quiz_div_o3: "Selling crops to different mandis", quiz_div_o4: "Using multiple types of chemical fertilizers", quiz_div_exp: "Growing different crops ensures that if one fails due to disease or weather, the others might still survive.",
        quiz_inf_q: "Why is keeping all your savings as cash in a box at home a bad idea?", quiz_inf_o1: "Cash loses value over time due to inflation", quiz_inf_o2: "The bank will charge you a fee", quiz_inf_o3: "You cannot use cash to buy seeds", quiz_inf_o4: "It is bad luck", quiz_inf_exp: "Inflation means things get more expensive over time. Putting money in a Fixed Deposit (FD) helps it grow to beat inflation."
    },
    hi: {
        app_title: "कृषि-नीति", credit_score: "क्रेडिट स्कोर", season: "मौसम", start_season: "नया मौसम शुरू करें", goals: "जीवन के लक्ष्य", bank: "बैंक और सोना", schemes: "सरकारी योजनाएं", shop: "संपत्ति", reports: "रिपोर्ट्स", profile: "प्रोफ़ाइल", quit: "छोड़ें", confirm_quit: "क्या आप वाकई गेम छोड़ना चाहते हैं?", advisory: "कृषि मित्र सलाह", ui_back: "पीछे", ui_continue: "जारी रखें", ui_confirm: "पुष्टि करें", splash_subtitle: "कृषि और वित्त का खेल", unknown_phase: "अज्ञात चरण", ui_switch_lang: "भाषा बदलें", ui_restart_game: "गेम रीस्टार्ट करें", header_savings: "बचत", header_debt: "कर्ज", header_wellbeing: "सुख-समृद्धि",
        setup_title: "आपका खेत", setup_subtitle: "अपना खेत सेट करें", setup_land_size: "ज़मीन का साइज़", setup_farm_type: "खेती का प्रकार", goal_sel_title: "आपका सपना क्या है?", goal_sel_subtitle: "वित्तीय साक्षरता आपके लक्ष्य पूरे करने में मदद करती है।", goal_target: "लक्ष्य:", goal_main_badge: "मुख्य सपना", goals_avail_savings: "उपलब्ध बचत", goals_pay_achieve: "भुगतान करें और लक्ष्य पूरा करें", goals_need_more: "₹{val} और चाहिए", goals_completed: "लक्ष्य पूरा हुआ!",
        bank_title: "ग्रामीण बैंक", bank_avail_bal: "उपलब्ध शेष", bank_land_loan: "भूमि ऋण", bank_principal_left: "शेष मूलधन:", bank_season_emi: "सीज़न EMI:", bank_repay_prin: "मूलधन चुकाएं", bank_pay_btn: "चुकाएं", bank_fd: "फिक्स्ड डिपॉजिट", bank_fd_return: "10% रिटर्न", bank_locked: "लॉक किया गया:", bank_matures: "परिपक्व सीज़न", bank_invest_btn: "निवेश करें", bank_gold: "डिजिटल गोल्ड", bank_gold_held: "गोल्ड होल्डिंग:", bank_rate: "दर:", bank_grams: "ग्राम", bank_buy_btn: "खरीदें", bank_sell_btn: "बेचें",
        ui_scanning: "खेत की जांच हो रही है...", ui_stage: "चरण", ui_of: "में से", ui_what_do: "आप क्या करेंगे?", ui_free: "मुफ़्त", ui_harvest_ready: "फसल तैयार है!", ui_where_sell: "आप अपनी {val} कहाँ बेचना चाहते हैं?", ui_total_land: "कुल ज़मीन:", ui_acres: "एकड़", ui_base_price: "वर्तमान आधार मूल्य:", ui_per_unit: "/ यूनिट", ui_yield_warning: "घटनाओं के कारण, आपकी उपज कम है। परिवहन लागत पर नज़र रखें!", ui_select_mandi: "मंडी चुनें", ui_est_gross: "अनुमानित सकल आय", ui_transport_cost: "कुल परिवहन लागत", ui_est_net: "अनुमानित शुद्ध आय", ui_sell_here: "यहाँ बेचें", ui_harvest_report: "फसल रिपोर्ट", ui_season_results: "सीज़न {val} परिणाम", ui_net_profit: "शुद्ध लाभ", ui_crop_sales: "फसल बिक्री आय", ui_insurance_payout: "बीमा भुगतान", ui_total_expenses: "कुल खर्च", ui_sold_at: "यहाँ बेचा:", ui_new_savings: "नई बचत", ui_current_debt: "वर्तमान कर्ज", ui_outstanding_debt: "बकाया कर्ज:", ui_repay_warning: "पुनर्भुगतान आपके क्रेडिट स्कोर को प्रभावित करता है।", ui_pay_full: "पूरी राशि चुकाएं", ui_score_plus_50: "(+50 स्कोर)", ui_pay_interest: "केवल ब्याज चुकाएं", ui_score_minus_10: "(-10 स्कोर)", ui_defer_pay: "भुगतान टालें (डिफ़ॉल्ट जोखिम)", ui_check_resilience: "रेज़िलिएंस स्कोर जांचें",
        profile_farmer: "किसान", profile_resilience: "लचीलापन (Resilience)", profile_owned_assets: "स्वामित्व वाली संपत्ति", profile_no_assets: "अभी तक कोई संपत्ति नहीं खरीदी। दुकान पर जाएँ!", reports_empty: "अभी तक कोई फसल इतिहास नहीं।", resil_title: "वित्तीय लचीलापन", resil_index: "सूचकांक", resil_savings: "बचत अनुशासन", resil_risk: "जोखिम की तैयारी", resil_debt: "कर्ज स्थिरता", resil_improve: "सुधार की आवश्यकता", resil_excellent: "उत्कृष्ट!", resil_good: "अच्छा, जारी रखें", resil_next_season: "अगला मौसम शुरू करें", vis_field_ready: "खेत बुवाई के लिए तैयार है", shop_buy_land_confirm: "1 एकड़ खरीदें? डाउन पेमेंट: ₹{down}। शेष ₹{loan} ऋण होगा।", plan_insufficient_funds: "अपर्याप्त धनराशि! {acres} एकड़ के लिए आपको ₹{cost} चाहिए।", goals_confirm_purchase: "{name} प्राप्त करने के लिए ₹{cost} खर्च करें?",
        crop_wheat: "गेहूँ", crop_cotton: "कपास", crop_soybean: "सोयाबीन", crop_onion: "प्याज़", crop_tomato: "टमाटर", type_crop: "फसल", type_veg: "सब्ज़ी", type_mixed: "मिश्रित",
        loan_kcc: "किसान क्रेडिट कार्ड", loan_coop: "सहकारी समिति", loan_sahukar: "स्थानीय साहूकार", ins_none: "कोई बीमा नहीं", ins_pmfby: "PMFBY बीमा",
        asset_type_infra: "बुनियादी ढांचा", asset_type_machinery: "मशीनरी", asset_drip: "ड्रिप सिंचाई", asset_drip_desc: "पानी बचाता है। सूखे के दौरान उपज की रक्षा करता है।", asset_tractor: "पावर टिलर", asset_tractor_desc: "श्रम लागत कम करता है।", asset_greenhouse: "पॉलीहाउस नेट", asset_greenhouse_desc: "सब्जियों को कीटों से बचाता है।", asset_solar: "सोलर पंप", asset_solar_desc: "सिंचाई के लिए मुफ्त बिजली।", asset_warehouse: "गोदाम", asset_warehouse_desc: "नुकसान से बचने के लिए फसलों को सुरक्षित रखें।",
        goal_tractor: "हैवी ड्यूटी ट्रैक्टर", goal_tractor_desc: "बड़े पैमाने पर खेती के लिए 45HP का ट्रैक्टर।", goal_edu: "बच्चों की उच्च शिक्षा", goal_edu_desc: "इंजीनियरिंग या मेडिकल कॉलेज की फीस।", goal_land: "पड़ोसी का खेत खरीदें", goal_land_desc: "अपने खेत का 5 एकड़ विस्तार करें।", goal_house: "पक्का घर बनाएं", goal_house_desc: "अपने परिवार की सुरक्षा के लिए कंक्रीट का घर।", goal_wedding: "भव्य विवाह", goal_wedding_desc: "एक सम्मानजनक विवाह समारोह।",
        mandi_local: "स्थानीय गांव APMC", mandi_local_desc: "अपने गांव में तुरंत बेचें। शून्य परिवहन लागत।", mandi_district: "जिला मुख्य मंडी", mandi_district_desc: "एक छोटा ट्रक किराए पर लें। कीमत और लागत का अच्छा संतुलन।", mandi_state: "राज्य कृषि बाजार", mandi_state_desc: "भारी परिवहन किराए पर लें। उच्चतम कीमतें, उच्च शुल्क।",
        sch_info: "सरकारी योजनाओं के लिए आवेदन करना मुफ्त है। ये वित्तीय सुरक्षा प्रदान करती हैं।", sch_eligibility: "पात्रता", sch_benefit: "लाभ", sch_enrolled: "नामांकित और सक्रिय", sch_apply: "अभी आवेदन करें", sch_not_eligible: "पात्र नहीं", sch_all_e: "सभी किसान पात्र हैं।",
        sch_pmkisan_n: "पीएम-किसान योजना", sch_pmkisan_d: "किसानों को आय सहायता प्रदान करने वाला प्रत्यक्ष लाभ हस्तांतरण (DBT)।", sch_pmkisan_b: "प्रति मौसम ₹2,000 सीधे बैंक खाते में।", sch_pmkisan_e: "5 एकड़ या उससे कम जमीन होनी चाहिए।",
        sch_pmfby_n: "PMFBY फसल बीमा", sch_pmfby_d: "प्राकृतिक आपदाओं से बचाता है।", sch_pmfby_b: "फसल बीमा प्रीमियम 50% कम करता है।",
        sch_miss_n: "MISS (ब्याज सब्सिडी)", sch_miss_d: "कृषि ऋणों के लिए ब्याज सब्सिडी।", sch_miss_b: "KCC ऋण ब्याज दर 7% से 4% तक कम करता है।", sch_miss_e: "क्रेडिट स्कोर 600+ आवश्यक है।",
        sch_soil_n: "मृदा स्वास्थ्य कार्ड", sch_soil_d: "उर्वरकों की सिफारिशें।", sch_soil_b: "फसल लागत 10% कम करता है।",
        sch_enam_n: "ई-नाम (e-NAM)", sch_enam_d: "राष्ट्रीय कृषि बाजार जो खरीदारों को डिजिटल रूप से जोड़ता है।", sch_enam_b: "फसल बिक्री मूल्य 10% बढ़ाता है।",
        sch_kusum_n: "PM-KUSUM सब्सिडी", sch_kusum_d: "सौर सिंचाई के लिए सरकारी सब्सिडी।", sch_kusum_b: "सोलर पंप खरीदने पर 50% छूट।",
        sch_drop_n: "पर ड्रॉप मोर क्रॉप", sch_drop_d: "सूक्ष्म सिंचाई प्रौद्योगिकियों को बढ़ावा देता है।", sch_drop_b: "ड्रिप सिंचाई खरीदने पर 50% की छूट।",
        sch_smam_n: "SMAM (मशीनीकरण)", sch_smam_d: "मशीनरी को किफायती बनाने का मिशन।", sch_smam_b: "मिनी ट्रैक्टर खरीदने पर 50% की छूट।",
        evt_fraud_title: "OTP स्कैम कॉल", evt_fraud_desc: "कॉलर बैंक मैनेजर होने का दावा करता है और OTP मांगता है।", evt_fraud_a: "कॉल काटें और ब्लॉक करें", evt_fraud_b: "OTP साझा करें",
        evt_seeds_title: "खराब अंकुरण", evt_seeds_desc: "बीज ठीक से अंकुरित नहीं हो रहे हैं।", evt_seeds_a: "खेत फिर से बोएं", evt_seeds_b: "प्रतीक्षा करें",
        evt_monsoon_title: "मानसून में देरी", evt_monsoon_desc: "बारिश में देरी हो रही है। मिट्टी सूख रही है।", evt_monsoon_a: "वाटर टैंकर किराए पर लें", evt_monsoon_b: "बारिश की उम्मीद करें",
        evt_theft_title: "नकदी का जोखिम", evt_theft_desc: "उर्वरक के लिए बड़ी नकदी ले जाना जोखिम भरा है।", evt_theft_a: "UPI के माध्यम से भुगतान करें", evt_theft_b: "नकद भुगतान करें",
        evt_pest_title: "कीट का हमला", evt_pest_desc: "कीड़े फसल को नुकसान पहुंचा रहे हैं।", evt_pest_a: "कीटनाशक स्प्रे करें", evt_pest_b: "घरेलू उपचार",
        evt_motor_title: "मोटर जल गई", evt_motor_desc: "वोल्टेज स्पाइक के कारण सिंचाई मोटर जल गई।", evt_motor_a: "तुरंत मरम्मत करें", evt_motor_b: "सिंचाई छोड़ें",
        evt_mandi_title: "व्यापारी बनाम मंडी", evt_mandi_desc: "स्थानीय व्यापारी तुरंत नकद लेकिन कम दरें प्रदान करता है।", evt_mandi_a: "मंडी में बेचें (UPI)", evt_mandi_b: "व्यापारी को बेचें",
        evt_hail_title: "ओलावृष्टि", evt_hail_desc: "कटाई से ठीक पहले भारी ओले!", evt_hail_a: "आपातकालीन कटाई", evt_hail_b: "कुछ न करें",
        evt_crash_title: "मूल्य में गिरावट", evt_crash_desc: "बाजार की कीमतें 40% तक गिर गईं।", evt_crash_a: "कोल्ड स्टोरेज का उपयोग करें", evt_crash_b: "कम कीमत पर बेचें",
        sum_complete: "सिमुलेशन पूर्ण", sum_identity: "आपकी वित्तीय पहचान", sum_report: "अंतिम रिपोर्ट कार्ड", sum_networth: "कुल निवल संपत्ति", sum_land: "स्वामित्व वाली भूमि", sum_goals: "लक्ष्य प्राप्त किए", sum_final_debt: "अंतिम कर्ज", sum_restart: "नई यात्रा शुरू करें",
        per_debt_t: "कर्जदार", per_debt_d: "आप बच गए, लेकिन ₹{val} कर्ज में। उच्च ब्याज वाले ऋणों ने आपका भविष्य खा लिया।", per_ratna_t: "कृषि रत्न", per_ratna_d: "खेती के मास्टर! आपने अपना सपना हासिल किया और अपार संपत्ति बनाई।", per_dream_t: "सपनों का पीछा करने वाला", per_dream_d: "बधाई हो! आपने अपना सपना हासिल किया: {val}। आप आर्थिक रूप से स्वतंत्र हैं।", per_zamin_t: "जमींदार", per_zamin_d: "आपने अपने खेत को {val} एकड़ तक बढ़ाया! आप क्षेत्र के सबसे बड़े जमींदार हैं।", per_invest_t: "समझदार निवेशक", per_invest_d: "आपने बैंक और फसलों के माध्यम से संपत्ति जमा की, लेकिन मुख्य लक्ष्य भूल गए।", per_bank_t: "बैंक का पसंदीदा", per_bank_d: "आपका क्रेडिट स्कोर त्रुटिहीन (800+) है। अगली बार तेजी से बढ़ने के लिए थोड़ा जोखिम लें।", per_survive_t: "जीवित रहने वाला", per_survive_d: "आपने {val} सीज़न पूरे किए। आपने तूफानों का सामना किया, लेकिन बस मुश्किल से।",
        adv_urgent_debt: "⚠️ ज़रूरी: आपका कर्ज बहुत अधिक है। पहले कर्ज चुकाएं!", adv_poverty_spiral: "🚨 चेतावनी: आप कर्ज के जाल में हैं! बैंक ऋण लें।", adv_use_score: "💡 4% KCC ऋण को प्राथमिकता दें।", adv_pm_kisan: "💡 सुझाव: ₹2,000 PM-KISAN का दावा करने के लिए योजनाएं देखें।", adv_fd_idle: "📈 सुझाव: आपके पास ₹{val} नकद है। इसे FD में डालें!", adv_soil_health: "🌱 सुझाव: उर्वरक लागत कम करने के लिए मृदा स्वास्थ्य कार्ड लें।", adv_pmfby: "🛡️ सुझाव: फसल बीमा पर 50% सब्सिडी के लिए PMFBY लें।", adv_improve_credit: "🏦 सुझाव: क्रेडिट स्कोर सुधारने के लिए ऋण चुकाएं।", adv_solar_kusum: "☀️ सुझाव: सोलर पंप पर छूट के लिए PM-KUSUM लागू करें!", adv_expand_land: "🚜 सुझाव: आप नई जमीन खरीद सकते हैं।", adv_buy_gold: "🪙 सुझाव: अपनी संपत्ति में विविधता लाएं! सोना खरीदें।", adv_gen_moneylender: "साहूकार का 36% ब्याज कर्ज के जाल में फंसाता है।", adv_gen_diversify: "फसल विविधीकरण मौसम के खिलाफ सबसे अच्छा बीमा है।", adv_gen_drip: "ड्रिप सिंचाई सूखे की चपेट को कम करती है।", adv_gen_transport: "बेचने से पहले बाजार परिवहन लागत की जांच करें।", adv_gen_praise: "🌟 बहुत बढ़िया! आपका खेत आर्थिक रूप से स्वस्थ है।",
        quiz_kcc_q: "किसान क्रेडिट कार्ड (KCC) का प्राथमिक लाभ क्या है?", quiz_kcc_o1: "मुफ्त ट्रैक्टर", quiz_kcc_o2: "कम ब्याज वाले कृषि ऋण", quiz_kcc_o3: "मौसम अपडेट", quiz_kcc_o4: "गारंटीकृत बाजार मूल्य", quiz_kcc_exp: "KCC किसानों को साहूकारों की तुलना में बहुत कम ब्याज दरों पर ऋण प्रदान करता है।",
        quiz_pmfby_q: "PMFBY योजना आपको किससे बचाती है?", quiz_pmfby_o1: "उपकरण की चोरी", quiz_pmfby_o2: "प्राकृतिक आपदाओं के कारण फसल का नुकसान", quiz_pmfby_o3: "चिकित्सा आपात स्थिति", quiz_pmfby_o4: "बाजार मूल्य में गिरावट", quiz_pmfby_exp: "PMFBY सरकार की फसल बीमा योजना है जो मौसम द्वारा फसल नष्ट होने पर रक्षा करती है।",
        quiz_compound_q: "साहूकार का 36% ब्याज दर बहुत खतरनाक क्यों है?", quiz_compound_o1: "कागजी कार्रवाई", quiz_compound_o2: "ऋण तेजी से बढ़ता है (कर्ज का जाल)", quiz_compound_o3: "केवल नकद ऋण", quiz_compound_o4: "बैंक से कोई अंतर नहीं", quiz_compound_exp: "उच्च ब्याज वाले ऋण तेजी से बढ़ते हैं, जिससे कर्ज का जाल बन जाता है।",
        quiz_div_q: "'फसल विविधीकरण' (Crop Diversification) क्या है?", quiz_div_o1: "एक ही फसल लगाना", quiz_div_o2: "जोखिम को फैलाने के लिए विभिन्न प्रकार की फसलें उगाना", quiz_div_o3: "अलग-अलग मंडियों में बेचना", quiz_div_o4: "रासायनिक उर्वरक", quiz_div_exp: "विभिन्न फसलें उगाने से यह सुनिश्चित होता है कि यदि एक फसल विफल हो जाती है, तो अन्य जीवित रह सकती हैं।",
        quiz_inf_q: "अपनी सारी बचत घर पर नकद में रखना बुरा विचार क्यों है?", quiz_inf_o1: "मुद्रास्फीति (महंगाई) के कारण नकद मूल्य खो देता है", quiz_inf_o2: "बैंक शुल्क लेगा", quiz_inf_o3: "बीज नहीं खरीद सकते", quiz_inf_o4: "बुरा शगुन", quiz_inf_exp: "महंगाई के कारण नकद का मूल्य घटता है। FD में पैसा रखने से मूल्य बढ़ता है।"
    },
    mr: {
        app_title: "कृषी-नीती", credit_score: "क्रेडिट स्कोअर", season: "हंगाम", start_season: "नवीन हंगाम सुरू करा", goals: "जीवनाची उद्दिष्टे", bank: "बँक आणि सोने", schemes: "सरकारी योजना", shop: "दुकान", reports: "अहवाल", profile: "प्रोफाइल", quit: "बाहेर पडा", confirm_quit: "तुम्हाला नक्की बाहेर पडायचे आहे का?", advisory: "कृषी मित्र सल्ला", ui_back: "मागे", ui_continue: "पुढे जा", ui_confirm: "निश्चित करा", splash_subtitle: "शेती आणि आर्थिक खेळ", unknown_phase: "अज्ञात टप्पा", ui_switch_lang: "भाषा बदला", ui_restart_game: "गेम पुन्हा सुरू करा", header_savings: "बचत", header_debt: "कर्ज", header_wellbeing: "सुख-समाधान",
        setup_title: "तुमचे शेत", setup_subtitle: "शेत तयार करा", setup_land_size: "जमिनीचा आकार", setup_farm_type: "शेतीचा प्रकार", goal_sel_title: "तुमचे स्वप्न काय आहे?", goal_sel_subtitle: "आर्थिक साक्षरता जीवन उद्दिष्टे साध्य करण्यास मदत करते.", goal_target: "लक्ष्य:", goal_main_badge: "मुख्य स्वप्न", goals_avail_savings: "उपलब्ध बचत", goals_pay_achieve: "पैसे द्या आणि ध्येय पूर्ण करा", goals_need_more: "अजून ₹{val} हवेत", goals_completed: "ध्येय पूर्ण झाले!",
        bank_title: "ग्रामीण बँक", bank_avail_bal: "उपलब्ध शिल्लक", bank_land_loan: "जमीन कर्ज", bank_principal_left: "उर्वरित मुद्दल:", bank_season_emi: "हंगाम EMI:", bank_repay_prin: "मुद्दल परत करा", bank_pay_btn: "पैसे द्या", bank_fd: "मुदत ठेव", bank_fd_return: "10% परतावा", bank_locked: "लॉक केलेले:", bank_matures: "परिपक्व हंगाम", bank_invest_btn: "गुंतवणूक करा", bank_gold: "डिजिटल सोने", bank_gold_held: "तुमचे सोने:", bank_rate: "दर:", bank_grams: "ग्रॅम", bank_buy_btn: "खरेदी करा", bank_sell_btn: "विक्री करा",
        ui_scanning: "शेताची तपासणी होत आहे...", ui_stage: "टप्पा", ui_of: "पैकी", ui_what_do: "तुम्ही काय कराल?", ui_free: "मोफत", ui_harvest_ready: "पीक तयार आहे!", ui_where_sell: "तुम्हाला तुमची {val} कुठे विकायची आहे?", ui_total_land: "एकूण जमीन:", ui_acres: "एकर", ui_base_price: "सध्याचा आधारभूत दर:", ui_per_unit: "/ युनिट", ui_yield_warning: "इव्हेंटमुळे तुमचे उत्पन्न कमी झाले आहे. वाहतूक खर्चावर लक्ष ठेवा!", ui_select_mandi: "मंडी निवडा", ui_est_gross: "अंदाजित ढोबळ उत्पन्न", ui_transport_cost: "एकूण वाहतूक खर्च", ui_est_net: "अंदाजित निव्वळ उत्पन्न", ui_sell_here: "येथे विका", ui_harvest_report: "कापणी अहवाल", ui_season_results: "हंगाम {val} निकाल", ui_net_profit: "निव्वळ नफा", ui_crop_sales: "पीक विक्री उत्पन्न", ui_insurance_payout: "विमा परतावा", ui_total_expenses: "एकूण खर्च", ui_sold_at: "येथे विकले:", ui_new_savings: "नवीन बचत", ui_current_debt: "सध्याचे कर्ज", ui_outstanding_debt: "थकीत कर्ज:", ui_repay_warning: "कर्ज परतफेडीचा क्रेडिट स्कोअरवर परिणाम होतो.", ui_pay_full: "पूर्ण रक्कम भरा", ui_score_plus_50: "(+50 स्कोअर)", ui_pay_interest: "फक्त व्याज भरा", ui_score_minus_10: "(-10 स्कोअर)", ui_defer_pay: "पेमेंट पुढे ढकला (डिफॉल्टचा धोका)", ui_check_resilience: "रेझिलिएन्स स्कोअर तपासा",
        profile_farmer: "शेतकरी", profile_resilience: "लवचिकता", profile_owned_assets: "मालकीची मालमत्ता", profile_no_assets: "अद्याप कोणतीही मालमत्ता खरेदी केलेली नाही. दुकानाला भेट द्या!", reports_empty: "अद्याप कोणताही पीक इतिहास नाही.", resil_title: "आर्थिक लवचिकता", resil_index: "इंडेक्स", resil_savings: "बचत शिस्त", resil_risk: "धोका पूर्वतयारी", resil_debt: "कर्ज स्थिरता", resil_improve: "सुधारणेची गरज", resil_excellent: "उत्कृष्ट!", resil_good: "छान, चालू ठेवा", resil_next_season: "पुढील हंगाम सुरू करा", vis_field_ready: "शेत पेरणीसाठी तयार आहे", shop_buy_land_confirm: "१ एकर खरेदी करायची? डाउन पेमेंट: ₹{down}. उर्वरित ₹{loan} कर्ज असेल.", plan_insufficient_funds: "अपुरी रक्कम! {acres} एकरांसाठी तुम्हाला ₹{cost} ची गरज आहे.", goals_confirm_purchase: "{name} साध्य करण्यासाठी ₹{cost} खर्च करायचे?",
        crop_wheat: "गहू", crop_cotton: "कापूस", crop_soybean: "सोयाबीन", crop_onion: "कांदा", crop_tomato: "टोमॅटो", type_crop: "पीक", type_veg: "भाजीपाला", type_mixed: "मिश्रित",
        loan_kcc: "किसान क्रेडिट कार्ड", loan_coop: "सहकारी संस्था", loan_sahukar: "सावकार", ins_none: "विमा नाही", ins_pmfby: "PMFBY विमा",
        asset_type_infra: "पायाभूत सुविधा", asset_type_machinery: "यंत्रसामग्री", asset_drip: "ठिबक सिंचन", asset_drip_desc: "पाण्याची बचत होते. दुष्काळात पिकांचे संरक्षण करते.", asset_tractor: "पॉवर टिलर", asset_tractor_desc: "मजुरीचा खर्च कमी करते.", asset_greenhouse: "पॉलीहाऊस नेट", asset_greenhouse_desc: "भाजीपाल्याचे कीटकांपासून संरक्षण करते.", asset_solar: "सौर पंप", asset_solar_desc: "सिंचनासाठी मोफत वीज.", asset_warehouse: "गोदाम", asset_warehouse_desc: "नुकसान टाळण्यासाठी पिके सुरक्षित साठवा.",
        goal_tractor: "मोठा ट्रॅक्टर", goal_tractor_desc: "मोठ्या शेतीसाठी 45HP ट्रॅक्टर.", goal_edu: "मुलांचे उच्च शिक्षण", goal_edu_desc: "इंजिनिअरिंग किंवा मेडिकल कॉलेजची फी.", goal_land: "शेजाऱ्याचे शेत खरेदी करा", goal_land_desc: "तुमची शेती 5 एकरांनी वाढवा.", goal_house: "पक्के घर बांधा", goal_house_desc: "कुटुंबाच्या संरक्षणासाठी पक्के घर.", goal_wedding: "भव्य विवाह", goal_wedding_desc: "एक सन्माननीय विवाह सोहळा.",
        mandi_local: "स्थानिक गाव APMC", mandi_local_desc: "तुमच्या गावात लगेच विका. शून्य वाहतूक खर्च.", mandi_district: "जिल्हा मुख्य मंडी", mandi_district_desc: "छोटा ट्रक भाड्याने घ्या. दर आणि खर्चाचे चांगले संतुलन.", mandi_state: "राज्य कृषी बाजार", mandi_state_desc: "अवजड वाहतूक भाड्याने घ्या. सर्वाधिक दर, जास्त खर्च.",
        sch_info: "सरकारी योजनांसाठी अर्ज करणे मोफत आहे. या योजना आर्थिक सुरक्षा देतात.", sch_eligibility: "पात्रता", sch_benefit: "फायदा", sch_enrolled: "नोंदणीकृत आणि सक्रिय", sch_apply: "आता अर्ज करा", sch_not_eligible: "पात्र नाही", sch_all_e: "सर्व शेतकरी पात्र आहेत.",
        sch_pmkisan_n: "PM-KISAN योजना", sch_pmkisan_d: "शेतकऱ्यांना थेट बँक खात्यात आर्थिक मदत.", sch_pmkisan_b: "दर हंगामात ₹२,००० थेट बँक खात्यात मिळतात.", sch_pmkisan_e: "जमीन ५ एकर किंवा त्याहून कमी असावी.",
        sch_pmfby_n: "PMFBY पीक विमा", sch_pmfby_d: "नैसर्गिक आपत्तींपासून संरक्षण.", sch_pmfby_b: "पीक विमा प्रीमियम ५०% ने कमी करतो.",
        sch_miss_n: "MISS (व्याज सवलत)", sch_miss_d: "अल्पावधी कृषी कर्जासाठी व्याज सवलत योजना.", sch_miss_b: "KCC कर्जाचा व्याजदर ७% वरून ४% पर्यंत कमी करतो.", sch_miss_e: "क्रेडिट स्कोअर ६००+ आवश्यक.",
        sch_soil_n: "मृदा आरोग्य कार्ड", sch_soil_d: "पिकांनुसार खतांच्या शिफारसी देते.", sch_soil_b: "पिकाचा खर्च १०% ने कमी होतो.",
        sch_enam_n: "ई-नाम (e-NAM)", sch_enam_d: "शेतकऱ्यांना देशभरातील खरेदीदारांशी डिजिटल पद्धतीने जोडते.", sch_enam_b: "पिकाच्या विक्री दरात १०% वाढ.",
        sch_kusum_n: "PM-KUSUM सबसिडी", sch_kusum_d: "सौर सिंचनासाठी सरकारी सबसिडी योजना.", sch_kusum_b: "सौर पंप खरेदीवर ५०% सवलत.",
        sch_drop_n: "पर ड्रॉप मोर क्रॉप", sch_drop_d: "पाण्याची बचत करण्यासाठी सूक्ष्म सिंचनाला प्रोत्साहन.", sch_drop_b: "ठिबक सिंचन खरेदीवर ५०% सवलत.",
        sch_smam_n: "SMAM (यांत्रिकीकरण)", sch_smam_d: "शेतमजुरी कमी करण्यासाठी यंत्रसामग्री स्वस्त करण्याची योजना.", sch_smam_b: "मिनी ट्रॅक्टर खरेदीवर ५०% सवलत.",
        evt_fraud_title: "OTP स्कॅम कॉल", evt_fraud_desc: "कॉलर बँक मॅनेजर असल्याचे सांगतो आणि OTP मागतो.", evt_fraud_a: "कॉल कट करा आणि ब्लॉक करा", evt_fraud_b: "OTP शेअर करा",
        evt_seeds_title: "खराब उगवण", evt_seeds_desc: "बियाणे नीट उगवत नाहीत.", evt_seeds_a: "शेत पुन्हा पेरा", evt_seeds_b: "वाट पहा",
        evt_monsoon_title: "मान्सूनला उशीर", evt_monsoon_desc: "पावसाला उशीर होत आहे. जमीन कोरडी पडत आहे.", evt_monsoon_a: "पाण्याचा टँकर भाड्याने घ्या", evt_monsoon_b: "पावसाची आशा करा",
        evt_theft_title: "रोख रकमेचा धोका", evt_theft_desc: "खतासाठी मोठी रोख रक्कम घेऊन जाणे धोक्याचे आहे.", evt_theft_a: "UPI द्वारे पेमेंट करा", evt_theft_b: "रोख पेमेंट करा",
        evt_pest_title: "कीटकांचा हल्ला", evt_pest_desc: "कीटक पिकांचे नुकसान करत आहेत.", evt_pest_a: "कीटकनाशक फवारा", evt_pest_b: "घरगुती उपाय",
        evt_motor_title: "मोटार जळाली", evt_motor_desc: "व्होल्टेज वाढल्यामुळे सिंचनाची मोटार जळाली.", evt_motor_a: "त्वरित दुरुस्ती करा", evt_motor_b: "सिंचन टाळा",
        evt_mandi_title: "व्यापारी विरुद्ध मंडी", evt_mandi_desc: "स्थानिक व्यापारी त्वरित रोख रक्कम देतो पण दर कमी आहेत.", evt_mandi_a: "मंडीत विका (UPI)", evt_mandi_b: "व्यापाऱ्याला विका",
        evt_hail_title: "गारपीट", evt_hail_desc: "कापणीपूर्वीच जोरदार गारपीट!", evt_hail_a: "तातडीने कापणी करा", evt_hail_b: "काहीही करू नका",
        evt_crash_title: "दर कोसळले", evt_crash_desc: "बाजारभाव 40% ने खाली आले.", evt_crash_a: "कोल्ड स्टोरेज वापरा", evt_crash_b: "कमी दराने विका",
        sum_complete: "सिम्युलेशन पूर्ण झाले", sum_identity: "तुमची आर्थिक ओळख", sum_report: "अंतिम अहवाल", sum_networth: "एकूण संपत्ती", sum_land: "मालकीची जमीन", sum_goals: "उद्दिष्टे साध्य", sum_final_debt: "अंतिम कर्ज", sum_restart: "नवीन प्रवास सुरू करा",
        per_debt_t: "कर्जबाजारी", per_debt_d: "तुम्ही तग धरलात, पण ₹{val} कर्जात अडकलात. जास्त व्याजाच्या कर्जांनी तुमचे भविष्य खाल्ले.", per_ratna_t: "कृषी रत्न", per_ratna_d: "शेतीचे तज्ज्ञ! तुम्ही तुमचे स्वप्न पूर्ण केले आणि मोठी संपत्ती उभारली.", per_dream_t: "स्वप्न पूर्ण करणारा", per_dream_d: "अभिनंदन! तुम्ही तुमचे स्वप्न साध्य केले: {val}. तुम्ही आर्थिकदृष्ट्या स्वतंत्र आहात.", per_zamin_t: "जमीनदार", per_zamin_d: "तुम्ही तुमची शेती {val} एकरांपर्यंत वाढवली! तुम्ही क्षेत्रातील सर्वात मोठे जमीनदार आहात.", per_invest_t: "चतुर गुंतवणूकदार", per_invest_d: "तुम्ही बँक आणि पिकांमधून मोठी संपत्ती जमा केली, पण मुख्य ध्येय विसरलात.", per_bank_t: "बँकेचा आवडता", per_bank_d: "तुमचा क्रेडिट स्कोअर (८००+) उत्तम आहे. पुढच्या वेळी थोडी जोखीम घ्या.", per_survive_t: "तग धरणारा", per_survive_d: "तुम्ही {val} हंगाम पूर्ण केले. तुम्ही संकटांचा सामना केला, पण जेमतेम.",
        adv_urgent_debt: "⚠️ तातडीचे: तुमचे कर्ज खूप जास्त आहे. आधी कर्ज फेडा!", adv_poverty_spiral: "🚨 चेतावणी: तुम्ही कर्जाच्या सापळ्यात आहात! बँकेचे कर्ज घ्या.", adv_use_score: "💡 4% KCC कर्जाला प्राधान्य द्या.", adv_pm_kisan: "💡 टीप: ₹2,000 PM-KISAN मिळवण्यासाठी सरकारी योजनांना भेट द्या.", adv_fd_idle: "📈 टीप: तुमच्याकडे ₹{val} पडून आहेत. ते FD मध्ये गुंतवा!", adv_soil_health: "🌱 टीप: खताचा खर्च कमी करण्यासाठी सॉइल हेल्थ कार्ड काढा.", adv_pmfby: "🛡️ टीप: पीक विम्यावर 50% सबसिडीसाठी PMFBY मध्ये नोंदणी करा.", adv_improve_credit: "🏦 टीप: क्रेडिट स्कोअर सुधारण्यासाठी कर्ज वेळेवर फेडा.", adv_solar_kusum: "☀️ टीप: सोलर पंप वर सूट मिळवण्यासाठी आधी PM-KUSUM लागू करा!", adv_expand_land: "🚜 टीप: नवीन जमीन खरेदी करण्यासाठी तुमच्याकडे पैसे आहेत.", adv_buy_gold: "🪙 टीप: डिजिटल सोने खरेदी करा.", adv_gen_moneylender: "सावकाराचे 36% व्याज कर्जाच्या सापळ्यात अडकवते.", adv_gen_diversify: "पिकांमधील विविधता हा हवामानातील बदलांवरील सर्वोत्तम उपाय आहे.", adv_gen_drip: "ठिबक सिंचनामुळे दुष्काळाचा धोका कमी होतो.", adv_gen_transport: "विक्रीपूर्वी बाजारातील वाहतूक खर्च तपासा.", adv_gen_praise: "🌟 उत्कृष्ट! तुमचे शेत आर्थिकदृष्ट्या निरोगी आहे.",
        quiz_kcc_q: "किसान क्रेडिट कार्ड (KCC) चा मुख्य फायदा काय आहे?", quiz_kcc_o1: "मोफत ट्रॅक्टर", quiz_kcc_o2: "कमी व्याजाची कृषी कर्जे", quiz_kcc_o3: "हवामान अपडेट", quiz_kcc_o4: "हमी बाजारभाव", quiz_kcc_exp: "KCC शेतकऱ्यांना सावकारांच्या तुलनेत अतिशय कमी व्याजदरात कर्ज देते.",
        quiz_pmfby_q: "PMFBY योजना तुम्हाला कशापासून संरक्षण देते?", quiz_pmfby_o1: "उपकरणांची चोरी", quiz_pmfby_o2: "नैसर्गिक आपत्तीमुळे पिकांचे नुकसान", quiz_pmfby_o3: "वैद्यकीय आणीबाणी", quiz_pmfby_o4: "बाजारभाव घसरणे", quiz_pmfby_exp: "PMFBY ही सरकारची पीक विमा योजना आहे जी हवामान किंवा कीटकांनी पिके नष्ट केल्यास शेतकऱ्यांचे रक्षण करते.",
        quiz_compound_q: "सावकाराचा 36% व्याजदर अत्यंत धोकादायक का आहे?", quiz_compound_o1: "कागदपत्रे", quiz_compound_o2: "कर्ज वेगाने वाढते", quiz_compound_o3: "फक्त रोख", quiz_compound_o4: "बँकेपेक्षा वेगळे नाही", quiz_compound_exp: "जास्त व्याजाचे कर्ज वेगाने वाढते. 36% दराने घेतलेले कर्ज वेळेत फेडता येत नाही.",
        quiz_div_q: "'पीक विविधता' (Crop Diversification) म्हणजे काय?", quiz_div_o1: "एकच पीक घेणे", quiz_div_o2: "जोखीम कमी करण्यासाठी विविध प्रकारची पिके घेणे", quiz_div_o3: "वेगवेगळ्या मंडईत विकणे", quiz_div_o4: "रासायनिक खते", quiz_div_exp: "विविध पिके घेतल्याने एक पीक खराब झाले तरी दुसरे पीक जगण्याची शक्यता वाढते.",
        quiz_inf_q: "तुमची सर्व बचत घरात रोख स्वरूपात ठेवणे वाईट का आहे?", quiz_inf_o1: "महागाईमुळे रोख रकमेचे मूल्य कमी होते", quiz_inf_o2: "बँक शुल्क आकारेल", quiz_inf_o3: "बियाणे खरेदी करू शकत नाही", quiz_inf_o4: "वाईट शकुन", quiz_inf_exp: "महागाईमुळे वस्तू महाग होतात. मुदत ठेवीत (FD) पैसे ठेवल्याने त्याचे मूल्य वाढते."
    },
    te: {
        app_title: "కృషి-నీతి", credit_score: "క్రెడిట్ స్కోర్", season: "సీజన్", start_season: "కొత్త సీజన్", goals: "జీవిత లక్ష్యాలు", bank: "బ్యాంక్ & బంగారం", schemes: "పథకాలు", shop: "దుకాణం", reports: "నివేదికలు", profile: "ప్రొఫైల్", quit: "నిష్క్రమించు", confirm_quit: "మీరు నిష్క్రమించాలనుకుంటున్నారా?", advisory: "కృషి మిత్ర సలహా", ui_back: "వెనుకకు", ui_continue: "కొనసాగించు", ui_confirm: "నిర్ధారించు", splash_subtitle: "వ్యవసాయం మరియు ఆర్థిక ఆట", unknown_phase: "తెలియని దశ", ui_switch_lang: "భాషను మార్చండి", ui_restart_game: "గేమ్‌ని పునఃప్రారంభించండి", header_savings: "పొదుపు", header_debt: "అప్పు", header_wellbeing: "శ్రేయస్సు",
        setup_title: "మీ పొలం", setup_subtitle: "మీ పొలాన్ని సెటప్ చేయండి", setup_land_size: "భూమి పరిమాణం", setup_farm_type: "వ్యవసాయం రకం", goal_sel_title: "మీ కల ఏమిటి?", goal_sel_subtitle: "ఆర్థిక అక్షరాస్యత జీవిత లక్ష్యాలను సాధించడంలో సహాయపడుతుంది.", goal_target: "లక్ష్యం:", goal_main_badge: "ప్రధాన కల", goals_avail_savings: "అందుబాటులో ఉన్న పొదుపు", goals_pay_achieve: "చెల్లించి లక్ష్యాన్ని సాధించండి", goals_need_more: "ఇంకా ₹{val} కావాలి", goals_completed: "లక్ష్యం పూర్తయింది!",
        bank_title: "గ్రామీణ బ్యాంక్", bank_avail_bal: "అందుబాటులో ఉన్న నిల్వ", bank_land_loan: "భూమి రుణం", bank_principal_left: "మిగిలిన అసలు:", bank_season_emi: "సీజన్ EMI:", bank_repay_prin: "అసలు చెల్లించండి", bank_pay_btn: "చెల్లించు", bank_fd: "ఫిక్స్‌డ్ డిపాజిట్", bank_fd_return: "10% రాబడి", bank_locked: "లాక్ చేయబడింది:", bank_matures: "మెచ్యూర్ అయ్యే సీజన్", bank_invest_btn: "పెట్టుబడి", bank_gold: "డిజిటల్ బంగారం", bank_gold_held: "బంగారం నిల్వ:", bank_rate: "ధర:", bank_grams: "గ్రాములు", bank_buy_btn: "కొనుగోలు", bank_sell_btn: "అమ్మకం",
        ui_scanning: "పొలాన్ని స్కాన్ చేస్తున్నారు...", ui_stage: "దశ", ui_of: "లో", ui_what_do: "మీరు ఏమి చేస్తారు?", ui_free: "ఉచితం", ui_harvest_ready: "పంట సిద్ధంగా ఉంది!", ui_where_sell: "మీరు మీ {val} ని ఎక్కడ అమ్మాలనుకుంటున్నారు?", ui_total_land: "మొత్తం భూమి:", ui_acres: "ఎకరాలు", ui_base_price: "ప్రస్తుత ఆధార ధర:", ui_per_unit: "/ యూనిట్", ui_yield_warning: "ఈవెంట్‌ల కారణంగా మీ దిగుబడి తగ్గింది. రవాణా ఖర్చులను గమనించండి!", ui_select_mandi: "మండిని ఎంచుకోండి", ui_est_gross: "అంచనా వేసిన స్థూల ఆదాయం", ui_transport_cost: "మొత్తం రవాణా ఖర్చు", ui_est_net: "అంచనా వేసిన నికర ఆదాయం", ui_sell_here: "ఇక్కడ అమ్మండి", ui_harvest_report: "పంట నివేదిక", ui_season_results: "సీజన్ {val} ఫలితాలు", ui_net_profit: "నికర లాభం", ui_crop_sales: "పంట అమ్మకాల ఆదాయం", ui_insurance_payout: "బీమా చెల్లింపు", ui_total_expenses: "మొత్తం ఖర్చులు", ui_sold_at: "ఇక్కడ అమ్మబడింది:", ui_new_savings: "కొత్త పొదుపు", ui_current_debt: "ప్రస్తుత అప్పు", ui_outstanding_debt: "బకాయి ఉన్న అప్పు:", ui_repay_warning: "చెల్లింపు మీ క్రెడిట్ స్కోర్‌ను ప్రభావితం చేస్తుంది.", ui_pay_full: "పూర్తి మొత్తం చెల్లించండి", ui_score_plus_50: "(+50 స్కోర్)", ui_pay_interest: "వడ్డీ మాత్రమే చెల్లించండి", ui_score_minus_10: "(-10 స్కోర్)", ui_defer_pay: "చెల్లింపు వాయిదా (డిఫాల్ట్ రిస్క్)", ui_check_resilience: "రెసిలియన్స్ స్కోర్ తనిఖీ చేయండి",
        profile_farmer: "రైతు", profile_resilience: "స్థితిస్థాపకత", profile_owned_assets: "స్వంత ఆస్తులు", profile_no_assets: "ఇంకా ఆస్తులు కొనలేదు. దుకాణాన్ని సందర్శించండి!", reports_empty: "ఇంకా పంట చరిత్ర లేదు.", resil_title: "ఆर्थिक స్థితిస్థాపకత", resil_index: "సూచిక", resil_savings: "పొదుపు క్రమశిక్షణ", resil_risk: "ప్రమాద సంసిద్ధత", resil_debt: "అప్పుల స్థిరత్వం", resil_improve: "మెరుగుపడాలి", resil_excellent: "అద్భుతం!", resil_good: "బాగుంది, కొనసాగించండి", resil_next_season: "తదుపరి సీజన్ ప్రారంభించండి", vis_field_ready: "పొలం విత్తడానికి సిద్ధంగా ఉంది", shop_buy_land_confirm: "1 ఎకరం కొనాలా? డౌన్ పేమెంట్: ₹{down}. మిగిలిన ₹{loan} అప్పు అవుతుంది.", plan_insufficient_funds: "సరిపడా నిధులు లేవు! {acres} ఎకరాలకు మీకు ₹{cost} కావాలి.", goals_confirm_purchase: "{name} సాధించడానికి ₹{cost} ఖర్చు చేయాలా?",
        crop_wheat: "గోధుమ", crop_cotton: "పత్తి", crop_soybean: "సోయాబీన్", crop_onion: "ఉల్లిపాయ", crop_tomato: "టమోటా", type_crop: "పంట", type_veg: "కూరగాయ", type_mixed: "మిశ్రమ",
        loan_kcc: "కిసాన్ క్రెడిట్ కార్డ్", loan_coop: "సహకార సంఘం", loan_sahukar: "వడ్డీ వ్యాపారి", ins_none: "బీమా లేదు", ins_pmfby: "PMFBY బీమా",
        asset_type_infra: "మౌలిక సదుపాయాలు", asset_type_machinery: "యంత్రాలు", asset_drip: "బిందు సేద్యం", asset_drip_desc: "నీటిని ఆదా చేస్తుంది. కరువుల నుండి రక్షిస్తుంది.", asset_tractor: "పవర్ టిల్లర్", asset_tractor_desc: "శ్రమ వ్యయాన్ని తగ్గిస్తుంది.", asset_greenhouse: "పాలీహౌస్ నెట్", asset_greenhouse_desc: "తెగుళ్ళ నుండి కూరగాయలను రక్షిస్తుంది.", asset_solar: "సోలార్ పంప్", asset_solar_desc: "ఉచిత విద్యుత్.", asset_warehouse: "గిడ్డంగి", asset_warehouse_desc: "పంటలను సురక్షితంగా నిల్వ చేయండి.",
        goal_tractor: "హెవీ డ్యూటీ ట్రాక్టర్", goal_tractor_desc: "పెద్ద ఎత్తున వ్యవసాయం కోసం 45HP ట్రాక్టర్.", goal_edu: "పిల్లల ఉన్నత విద్య", goal_edu_desc: "ఇంజనీరింగ్ లేదా మెడికల్ కాలేజీ ఫీజులు.", goal_land: "పొరుగువారి పొలం కొనుగోలు", goal_land_desc: "మీ పొలాన్ని 5 ఎకరాలు విస్తరించండి.", goal_house: "పక్కా ఇల్లు నిర్మించు", goal_house_desc: "మీ కుటుంబాన్ని రక్షించడానికి కాంక్రీట్ ఇల్లు.", goal_wedding: "గ్రాండ్ వెడ్డింగ్", goal_wedding_desc: "ఒక గౌరవప్రదమైన వివాహ వేడుక.",
        mandi_local: "స్థానిక గ్రామ APMC", mandi_local_desc: "మీ గ్రామంలో వెంటనే అమ్మండి. రవాణా ఖర్చులు సున్నా.", mandi_district: "జిల్లా ప్రధాన మండి", mandi_district_desc: "చిన్న ట్రక్కును అద్దెకు తీసుకోండి. ధర మరియు ఖర్చు మధ్య మంచి బ్యాలెన్స్.", mandi_state: "రాష్ట్ర వ్యవసాయ మార్కెట్", mandi_state_desc: "భారీ రవాణాను అద్దెకు తీసుకోండి. అత్యధిక ధరలు, అధిక ఫీజులు.",
        sch_info: "ప్రభుత్వ పథకాలకు దరఖాస్తు చేసుకోవడం ఉచితం. ఇవి ఆర్థిక భద్రతను అందిస్తాయి.", sch_eligibility: "అర్హత", sch_benefit: "ప్రయోజనం", sch_enrolled: "నమోదై చురుకుగా ఉంది", sch_apply: "ఇప్పుడే దరఖాస్తు చేయండి", sch_not_eligible: "అర్హత లేదు", sch_all_e: "రైతులందరూ అర్హులు.",
        sch_pmkisan_n: "PM-కిసాన్ యోజన", sch_pmkisan_d: "రైతులకు ఆదాయ మద్దతును అందించే డైరెక్ట్ బెనిఫిట్ ట్రాన్స్‌ఫర్ (DBT).", sch_pmkisan_b: "ప్రతి సీజన్‌కు ₹2,000 నేరుగా బ్యాంకు ఖాతాలో పడతాయి.", sch_pmkisan_e: "5 ఎకరాలు లేదా అంతకంటే తక్కువ భూమి ఉండాలి.",
        sch_pmfby_n: "PMFBY పంట బీమా", sch_pmfby_d: "ప్రకృతి వైపరీత్యాల నుండి రక్షిస్తుంది.", sch_pmfby_b: "పంట బీమా ప్రీమియంలను 50% తగ్గిస్తుంది.",
        sch_miss_n: "MISS (వడ్డీ రాయితీ)", sch_miss_d: "వ్యవసాయ రుణాల కోసం వడ్డీ రాయితీ పథకం.", sch_miss_b: "KCC వడ్డీ రేటును 7% నుండి 4% కి తగ్గిస్తుంది.", sch_miss_e: "క్రెడిట్ స్కోర్ 600+ అవసరం.",
        sch_soil_n: "సాయిల్ హెల్త్ కార్డ్", sch_soil_d: "ఎరువుల సిఫార్సులను అందిస్తుంది.", sch_soil_b: "పంట పెట్టుబడి ఖర్చులను 10% తగ్గిస్తుంది.",
        sch_enam_n: "ఈ-నామ్ (e-NAM)", sch_enam_d: "కొనుగోలుదారులతో డిజిటల్‌గా కలుపుతుంది.", sch_enam_b: "పంట అమ్మకపు ధరను 10% పెంచుతుంది.",
        sch_kusum_n: "PM-KUSUM సబ్సిడీ", sch_kusum_d: "సౌర సేద్యం కోసం ప్రభుత్వ సబ్సిడీ.", sch_kusum_b: "సోలార్ పంప్ కొనుగోలుపై 50% తగ్గింపు.",
        sch_drop_n: "పెర్ డ్రాప్ మోర్ క్రాప్", sch_drop_d: "సూక్ష్మ సేద్యాన్ని ప్రోత్సహిస్తుంది.", sch_drop_b: "డ్రిప్ ఇరిగేషన్ కొనుగోలుపై 50% తగ్గింపు.",
        sch_smam_n: "SMAM (యాంత్రీకరణ)", sch_smam_d: "యంత్రాలను సరసమైన ధరలకు అందించే మిషన్.", sch_smam_b: "మినీ ట్రాక్టర్ కొనుగోలుపై 50% తగ్గింపు.",
        evt_fraud_title: "OTP స్కామ్ కాల్", evt_fraud_desc: "కాలర్ బ్యాంక్ మేనేజర్ అని చెబుతూ OTP అడుగుతున్నాడు.", evt_fraud_a: "కాల్ కట్ చేసి బ్లాక్ చేయి", evt_fraud_b: "OTP పంచుకోండి",
        evt_seeds_title: "పేలవమైన అంకురోత్పత్తి", evt_seeds_desc: "విత్తనాలు సరిగ్గా మొలకెత్తడం లేదు.", evt_seeds_a: "మళ్ళీ విత్తు", evt_seeds_b: "వేచి చూడు",
        evt_monsoon_title: "వర్షాకాలం ఆలస్యం", evt_monsoon_desc: "వర్షాలు ఆలస్యమయ్యాయి. నేల ఎండిపోతోంది.", evt_monsoon_a: "వాటర్ ట్యాంకర్ అద్దెకు తీసుకో", evt_monsoon_b: "వర్షం కోసం ఎదురుచూడు",
        evt_theft_title: "నగదు ప్రమాదం", evt_theft_desc: "ఎరువుల కోసం పెద్ద మొత్తంలో నగదు తీసుకెళ్లడం ప్రమాదకరం.", evt_theft_a: "UPI ద్వారా చెల్లించండి", evt_theft_b: "నగదు చెల్లించండి",
        evt_pest_title: "తెగులు దాడి", evt_pest_desc: "పురుగులు పంటను నాశనం చేస్తున్నాయి.", evt_pest_a: "క్రిమిసంహారక మందు పిచికారీ", evt_pest_b: "ఇంటి నివారణ",
        evt_motor_title: "మోటార్ కాలిపోయింది", evt_motor_desc: "వోల్టేజ్ పెరగడం వల్ల నీటి మోటార్ కాలిపోయింది.", evt_motor_a: "వెంటనే రిపేర్ చేయించు", evt_motor_b: "నీరు పెట్టడం మానేయి",
        evt_mandi_title: "వ్యాపారి vs మండి", evt_mandi_desc: "స్థానిక వ్యాపారి వెంటనే నగదు ఇస్తాడు కానీ తక్కువ ధర ఇస్తాడు.", evt_mandi_a: "మండిలో అమ్మండి (UPI)", evt_mandi_b: "వ్యాపారికి అమ్మండి",
        evt_hail_title: "వడగళ్ళు", evt_hail_desc: "పంట కోతకు ముందు భారీ వడగళ్ళు!", evt_hail_a: "అత్యవసర కోత", evt_hail_b: "ఏమీ చేయవద్దు",
        evt_crash_title: "ధరల పతనం", evt_crash_desc: "మార్కెట్ ధరలు 40% పడిపోయాయి.", evt_crash_a: "కోల్డ్ స్టోరేజ్ వాడండి", evt_crash_b: "తక్కువ ధరకు అమ్మండి",
        sum_complete: "సిమ్యులేషన్ పూర్తయింది", sum_identity: "మీ ఆర్థిక గుర్తింపు", sum_report: "తుది నివేదిక", sum_networth: "మొత్తం ఆస్తులు", sum_land: "సొంత భూమి", sum_goals: "సాధించిన లక్ష్యాలు", sum_final_debt: "చివరి అప్పు", sum_restart: "కొత్త ప్రయాణాన్ని ప్రారంభించండి",
        per_debt_t: "అప్పులపాలైన వ్యక్తి", per_debt_d: "మీరు బతికారు, కానీ ₹{val} అప్పులతో. అధిక వడ్డీ రుణాలు మీ భవిష్యత్తును తినేశాయి.", per_ratna_t: "కృషి రత్న", per_ratna_d: "వ్యవసాయంలో మాస్టర్! మీరు మీ కలను సాధించారు మరియు భారీ ఆస్తులను నిర్మించారు.", per_dream_t: "కలలు సాధించినవాడు", per_dream_d: "అభినందనలు! మీరు మీ కలను సాధించారు: {val}. మీరు ఆర్థికంగా స్వేచ్ఛగా ఉన్నారు.", per_zamin_t: "జమీందార్", per_zamin_d: "మీరు మీ పొలాన్ని {val} ఎకరాలకు పెంచారు! మీరే అతిపెద్ద భూస్వామి.", per_invest_t: "తెలివైన పెట్టుబడిదారుడు", per_invest_d: "మీరు బ్యాంకు ద్వారా గొప్ప సంపదను కూడబెట్టారు, కానీ ప్రధాన లక్ష్యాన్ని మర్చిపోయారు.", per_bank_t: "బ్యాంక్ ఫేవరెట్", per_bank_d: "మీ క్రెడిట్ స్కోర్ అద్భుతంగా ఉంది (800+). తదుపరిసారి కొంచెం రిస్క్ తీసుకోండి.", per_survive_t: "బతికినవాడు", per_survive_d: "మీరు {val} సీజన్లు పూర్తి చేసారు. కష్టాలను ఎదుర్కొన్నారు.",
        adv_urgent_debt: "⚠️ అత్యవసరం: మీ అప్పు ప్రమాదకరంగా ఉంది. ముందు అప్పు తీర్చండి!", adv_poverty_spiral: "🚨 హెచ్చరిక: మీరు అప్పుల ఊబిలో ఉన్నారు! బ్యాంక్ రుణాలను ఆశ్రయించండి.", adv_use_score: "💡 4% KCC రుణానికి ప్రాధాన్యత ఇవ్వండి.", adv_pm_kisan: "💡 చిట్కా: ₹2,000 PM-KISAN పొందడానికి పథకాలను సందర్శించండి.", adv_fd_idle: "📈 చిట్కా: మీ దగ్గర ₹{val} నగదు ఉంది. దానిని FDలో పెట్టండి!", adv_soil_health: "🌱 చిట్కా: ఎరువుల ఖర్చు తగ్గించుకోవడానికి సాయిల్ హెల్త్ కార్డ్ పొందండి.", adv_pmfby: "🛡️ చిట్కా: 50% సబ్సిడీ కోసం PMFBY లో నమోదు చేసుకోండి.", adv_improve_credit: "🏦 చిట్కా: క్రెడిట్ స్కోర్‌ను మెరుగుపరచడానికి రుణాలను తీర్చండి.", adv_solar_kusum: "☀️ చిట్కా: సోలార్ పంప్ రాయితీ కోసం PM-KUSUM కు దరఖాస్తు చేయండి!", adv_expand_land: "🚜 చిట్కా: కొత్త భూమి కొనడానికి మీ వద్ద తగినంత డబ్బు ఉంది.", adv_buy_gold: "🪙 చిట్కా: డిజిటల్ బంగారం కొనండి.", adv_gen_moneylender: "వడ్డీ వ్యాపారి 36% వడ్డీ మిమ్మల్ని అప్పులపాలు చేస్తుంది.", adv_gen_diversify: "పంటల వైవిధ్యం వాతావరణ మార్పుల నుండి రక్షిస్తుంది.", adv_gen_drip: "బిందు సేద్యం కరువు ప్రభావాన్ని తగ్గిస్తుంది.", adv_gen_transport: "అమ్మే ముందు రవాణా ఖర్చులను తనిఖీ చేయండి.", adv_gen_praise: "🌟 అద్భుతం! మీ పొలం ఆర్థికంగా బలంగా ఉంది.",
        quiz_kcc_q: "కిసాన్ క్రెడిట్ కార్డ్ (KCC) యొక్క ప్రధాన ప్రయోజనం ఏమిటి?", quiz_kcc_o1: "ఉచిత ట్రాక్టర్", quiz_kcc_o2: "తక్కువ వడ్డీ రుణాలు", quiz_kcc_o3: "వాతావరణ అప్‌డేట్‌లు", quiz_kcc_o4: "మార్కెట్ ధరలు", quiz_kcc_exp: "సాధారణ వడ్డీ వ్యాపారులతో పోలిస్తే KCC చాలా తక్కువ వడ్డీ రేట్లతో రుణాలను అందిస్తుంది.",
        quiz_pmfby_q: "PMFBY పథకం మిమ్మల్ని దేని నుండి రక్షిస్తుంది?", quiz_pmfby_o1: "దొంగతనం", quiz_pmfby_o2: "ప్రకృతి విపత్తుల వలన పంట నష్టం", quiz_pmfby_o3: "వైద్య ఖర్చులు", quiz_pmfby_o4: "మార్కెట్ ధరలు తగ్గడం", quiz_pmfby_exp: "వాతావరణం లేదా తెగుళ్ల వల్ల పంట నష్టపోతే రైతులను ఆర్థికంగా ఆదుకునే పథకం PMFBY.",
        quiz_compound_q: "వడ్డీ వ్యాపారి 36% వడ్డీ ఎందుకు ప్రమాదకరం?", quiz_compound_o1: "కాगితపు పని", quiz_compound_o2: "అప్పు వేగంగా పెరుగుతుంది", quiz_compound_o3: "నగదు మాత్రమే", quiz_compound_o4: "బ్యాంకుకు తేడా లేదు", quiz_compound_exp: "అధిక వడ్డీ రుణాలు వేగంగా పెరుగుతాయి. 36% వడ్డీ రైతులను శాశ్వత అప్పుల ఊబిలో బంధిస్తుంది.",
        quiz_div_q: "'పంటల వైవిధ్యం' (Crop Diversification) అంటే ఏమిటి?", quiz_div_o1: "ఒకే పంట వేయడం", quiz_div_o2: "నష్టాన్ని తగ్గించడానికి వివిధ పంటలను పండించడం", quiz_div_o3: "వేరే మార్కెట్‌లో అమ్మడం", quiz_div_o4: "రసాయన ఎరువులు", quiz_div_exp: "వివిధ రకాల పంటలను పండించడం వల్ల ఒక పంట దెబ్బతిన్నా మరో పంట కాపాడుతుంది.",
        quiz_inf_q: "మీ పొదుపు మొత్తాన్ని ఇంట్లో ఉంచడం ఎందుకు మంచిది కాదు?", quiz_inf_o1: "ద్రవ్యోల్బణం కారణంగా నగదు విలువ తగ్గుతుంది", quiz_inf_o2: "బ్యాంక్ ఫీజు వసూలు చేస్తుంది", quiz_inf_o3: "విత్తనాలు కొనలేము", quiz_inf_o4: "దురదృష్టం", quiz_inf_exp: "ద్రవ్యోల్బణం అంటే కాలక్రమేణా వస్తువులు ఖరీదైనవి కావడం. FD లో డబ్బు పెడితే అది పెరుగుతుంది."
    },
    ta: {
        app_title: "கிருஷி-நீதி", credit_score: "கடன் மதிப்பெண்", season: "பருவம்", start_season: "புதிய பருவம்", goals: "இலக்குகள்", bank: "வங்கி & தங்கம்", schemes: "அரசு திட்டங்கள்", shop: "கடை", reports: "அறிக்கைகள்", profile: "சுயவிவரம்", quit: "வெளியேறு", confirm_quit: "நிச்சயமாக வெளியேற வேண்டுமா?", advisory: "கிருஷி மித்ரா ஆலோசனை", ui_back: "பின்செல்", ui_continue: "தொடரவும்", ui_confirm: "உறுதி செய்", splash_subtitle: "விவசாயம் மற்றும் நிதி விளையாட்டு", unknown_phase: "தெரியாத நிலை", ui_switch_lang: "மொழியை மாற்று", ui_restart_game: "விளையாட்டை மீண்டும் தொடங்கு", header_savings: "சேமிப்பு", header_debt: "கடன்", header_wellbeing: "நல்வாழ்வு",
        setup_title: "உங்கள் பண்ணை", setup_subtitle: "உங்கள் பண்ணையை அமைக்கவும்", setup_land_size: "நில அளவு", setup_farm_type: "விவசாய வகை", goal_sel_title: "உங்கள் கனவு என்ன?", goal_sel_subtitle: "வாழ்க்கை இலக்குகளை அடைய நிதி அறிவு உதவுகிறது.", goal_target: "இலக்கு:", goal_main_badge: "முக்கிய கனவு", goals_avail_savings: "கிடைக்கக்கூடிய சேமிப்பு", goals_pay_achieve: "செலுத்தி இலக்கை அடையுங்கள்", goals_need_more: "இன்னும் ₹{val} தேவை", goals_completed: "இலக்கு முடிந்தது!",
        bank_title: "கிராம வங்கி", bank_avail_bal: "இருப்புத் தொகை", bank_land_loan: "நிலக் கடன்", bank_principal_left: "மீதமுள்ள அசல்:", bank_season_emi: "பருவ EMI:", bank_repay_prin: "அசலைத் திருப்பிச் செலுத்து", bank_pay_btn: "செலுத்து", bank_fd: "நிலையான வைப்பு", bank_fd_return: "10% வருவாய்", bank_locked: "பூட்டப்பட்டது:", bank_matures: "முதிர்ச்சியடையும் பருவம்", bank_invest_btn: "முதலீடு செய்", bank_gold: "டிஜிட்டல் தங்கம்", bank_gold_held: "தங்க இருப்பு:", bank_rate: "விலை:", bank_grams: "கிராம்", bank_buy_btn: "வாங்கு", bank_sell_btn: "விற்க",
        ui_scanning: "பண்ணையை சோதிக்கிறது...", ui_stage: "நிலை", ui_of: "இல்", ui_what_do: "நீங்கள் என்ன செய்வீர்கள்?", ui_free: "இலவசம்", ui_harvest_ready: "அறுவடைக்கு தயார்!", ui_where_sell: "உங்கள் {val} எங்கே விற்க விரும்புகிறீர்கள்?", ui_total_land: "மொத்த நிலம்:", ui_acres: "ஏக்கர்", ui_base_price: "தற்போதைய அடிப்படை விலை:", ui_per_unit: "/ யூனிட்", ui_yield_warning: "நிகழ்வுகளால் உங்கள் விளைச்சல் குறைந்துள்ளது. போக்குவரத்து செலவுகளை கவனிக்கவும்!", ui_select_mandi: "சந்தையைத் தேர்ந்தெடுக்கவும்", ui_est_gross: "மதிப்பிடப்பட்ட மொத்த வருமானம்", ui_transport_cost: "மொத்த போக்குவரத்து செலவு", ui_est_net: "மதிப்பிடப்பட்ட நிகர வருமானம்", ui_sell_here: "இங்கே விற்கவும்", ui_harvest_report: "அறுவடை அறிக்கை", ui_season_results: "பருவம் {val} முடிவுகள்", ui_net_profit: "நிகர லாபம்", ui_crop_sales: "பயிர் விற்பனை வருமானம்", ui_insurance_payout: "காப்பீட்டுத் தொகை", ui_total_expenses: "மொத்த செலவுகள்", ui_sold_at: "விற்கப்பட்ட இடம்:", ui_new_savings: "புதிய சேமிப்பு", ui_current_debt: "தற்போதைய கடன்", ui_outstanding_debt: "நிலுவையில் உள்ள கடன்:", ui_repay_warning: "திரும்பச் செலுத்துதல் உங்கள் கடன் மதிப்பெண்ணை பாதிக்கும்.", ui_pay_full: "முழு தொகையையும் செலுத்துங்கள்", ui_score_plus_50: "(+50 மதிப்பெண்)", ui_pay_interest: "வட்டியை மட்டும் செலுத்துங்கள்", ui_score_minus_10: "(-10 மதிப்பெண்)", ui_defer_pay: "பணம் செலுத்த தாமதம் (இயல்புநிலை ஆபத்து)", ui_check_resilience: "நெகிழ்வுத்தன்மை மதிப்பெண்ணை சரிபார்க்கவும்",
        profile_farmer: "விவசாயி", profile_resilience: "நெகிழ்வுத்தன்மை", profile_owned_assets: "சொந்தமான சொத்துக்கள்", profile_no_assets: "சொத்துக்கள் எதுவும் வாங்கவில்லை. கடைக்குச் செல்லுங்கள்!", reports_empty: "இன்னும் அறுவடை வரலாறு இல்லை.", resil_title: "நிதி நெகிழ்வுத்தன்மை", resil_index: "குறியீடு", resil_savings: "சேமிப்பு ஒழுக்கம்", resil_risk: "ஆபத்து தயார்நிலை", resil_debt: "கடன் நிலைத்தன்மை", resil_improve: "மேம்படுத்த வேண்டும்", resil_excellent: "மிக நன்று!", resil_good: "நன்று, தொடரவும்", resil_next_season: "அடுத்த பருவத்தை தொடங்கு", vis_field_ready: "நிலம் விதைக்க தயாராக உள்ளது", shop_buy_land_confirm: "1 ஏக்கர் வாங்க வேண்டுமா? முன்பணம்: ₹{down}. மீதமுள்ள ₹{loan} கடனாக இருக்கும்.", plan_insufficient_funds: "போதிய நிதி இல்லை! {acres} ஏக்கருக்கு உங்களுக்கு ₹{cost} தேவை.", goals_confirm_purchase: "{name} ஐ அடைய ₹{cost} செலவழிக்கலாமா?",
        crop_wheat: "கோதுமை", crop_cotton: "பருத்தி", crop_soybean: "சோயாபீன்", crop_onion: "வெங்காயம்", crop_tomato: "தக்காளி", type_crop: "பயிர்", type_veg: "காய்கறி", type_mixed: "கலப்பு",
        loan_kcc: "கிசான் கிரெடிட் கார்டு", loan_coop: "கூட்டுறவு சங்கம்", loan_sahukar: "வட்டிக்கு பணம் தருபவர்", ins_none: "காப்பீடு இல்லை", ins_pmfby: "PMFBY காப்பீடு",
        asset_type_infra: "உள்கட்டமைப்பு", asset_type_machinery: "இயந்திரங்கள்", asset_drip: "சொட்டு நீர் பாசனம்", asset_drip_desc: "தண்ணீரை சேமிக்கிறது. வறட்சியிலிருந்து பாதுகாக்கிறது.", asset_tractor: "பவர் டில்லர்", asset_tractor_desc: "உழைப்பு செலவை குறைக்கிறது.", asset_greenhouse: "பாலிஹவுஸ் வலை", asset_greenhouse_desc: "பூச்சிகளிலிருந்து பாதுகாக்கிறது.", asset_solar: "சூரிய பம்ப்", asset_solar_desc: "இலவச மின்சாரம்.", asset_warehouse: "கிடங்கு", asset_warehouse_desc: "பயிர்களை பாதுகாப்பாக சேமிக்கவும்.",
        goal_tractor: "பெரிய டிராக்டர்", goal_tractor_desc: "பெரிய விவசாயத்திற்கு 45HP டிராக்டர்.", goal_edu: "குழந்தைகளின் உயர் கல்வி", goal_edu_desc: "பொறியியல் அல்லது மருத்துவ கல்லூரி கட்டணம்.", goal_land: "அண்டை நிலத்தை வாங்கு", goal_land_desc: "உங்கள் பண்ணையை 5 ஏக்கர் விரிவாக்குங்கள்.", goal_house: "கான்கிரீட் வீடு கட்டு", goal_house_desc: "உங்கள் குடும்பத்தை பாதுகாக்க வீடு.", goal_wedding: "பிரம்மாண்ட திருமணம்", goal_wedding_desc: "ஒரு மரியாதைக்குரிய திருமண விழா.",
        mandi_local: "உள்ளூர் கிராம APMC", mandi_local_desc: "உங்கள் கிராமத்திலேயே விற்கவும். போக்குவரத்து செலவு இல்லை.", mandi_district: "மாவட்ட பிரதான மண்டி", mandi_district_desc: "ஒரு சிறிய லாரியை வாடகைக்கு எடுக்கவும். விலை மற்றும் செலவு இடையே நல்ல சமநிலை.", mandi_state: "மாநில வேளாண் சந்தை", mandi_state_desc: "கனரக போக்குவரத்தை வாடகைக்கு எடுக்கவும். அதிக விலை, அதிக கட்டணம்.",
        sch_info: "அரசு திட்டங்களுக்கு விண்ணப்பிப்பது இலவசம். இவை நிதி பாதுகாப்பை வழங்குகின்றன.", sch_eligibility: "தகுதி", sch_benefit: "நன்மை", sch_enrolled: "பதிவுசெய்யப்பட்டு செயலில் உள்ளது", sch_apply: "இப்போதே விண்ணப்பிக்கவும்", sch_not_eligible: "தகுதியில்லை", sch_all_e: "அனைத்து விவசாயிகளுக்கும் தகுதி உண்டு.",
        sch_pmkisan_n: "PM-கிசான் திட்டம்", sch_pmkisan_d: "விவசாயிகளுக்கு வருமான ஆதரவை வழங்கும் நேரடி நன்மை பரிமாற்றம் (DBT).", sch_pmkisan_b: "ஒரு பருவத்திற்கு ₹2,000 நேரடியாக வங்கி கணக்கில் கிடைக்கும்.", sch_pmkisan_e: "5 ஏக்கர் அல்லது அதற்கும் குறைவான நிலம் இருக்க வேண்டும்.",
        sch_pmfby_n: "PMFBY பயிர் காப்பீடு", sch_pmfby_d: "இயற்கை பேரழிவுகளிலிருந்து பாதுகாக்கிறது.", sch_pmfby_b: "பயிர் காப்பீட்டு பிரீமியத்தை 50% குறைக்கிறது.",
        sch_miss_n: "MISS (வட்டி மானியம்)", sch_miss_d: "குறுகிய கால விவசாய கடன்களுக்கான வட்டி மானியத் திட்டம்.", sch_miss_b: "KCC கடன் வட்டி விகிதத்தை 7% இலிருந்து 4% ஆக குறைக்கிறது.", sch_miss_e: "600+ கடன் மதிப்பெண் தேவை.",
        sch_soil_n: "மண் வள அட்டை", sch_soil_d: "பயிருக்குத் தேவையான உரப் பரிந்துரைகளை வழங்குகிறது.", sch_soil_b: "பயிர் இடுபொருள் செலவை 10% குறைக்கிறது.",
        sch_enam_n: "இ-நாம் (e-NAM)", sch_enam_d: "விவசாயிகளை வாங்குபவர்களுடன் டிஜிட்டல் முறையில் இணைக்கிறது.", sch_enam_b: "பயிர் விற்பனை விலையை 10% அதிகரிக்கிறது.",
        sch_kusum_n: "PM-KUSUM மானியம்", sch_kusum_d: "சூரிய ஒளி பாசனத்திற்கான அரசு மானியத் திட்டம்.", sch_kusum_b: "சூரிய பம்ப் வாங்கும்போது மூலதன செலவில் 50% தள்ளுபடி.",
        sch_drop_n: "பெர் ட்ராப் மோர் க்ராப்", sch_drop_d: "நுண்ணீர் பாசனத்தை ஊக்குவிக்கிறது.", sch_drop_b: "சொட்டு நீர் பாசனம் வாங்கும்போது 50% தள்ளுபடி.",
        sch_smam_n: "SMAM (இயந்திரமயமாக்கல்)", sch_smam_d: "இயந்திரங்களை மலிவாக வழங்கும் திட்டம்.", sch_smam_b: "மினி டிராக்டர் வாங்கும்போது 50% தள்ளுபடி.",
        evt_fraud_title: "OTP மோசடி அழைப்பு", evt_fraud_desc: "வங்கி மேலாளர் என்று கூறி OTP கேட்கிறார்கள்.", evt_fraud_a: "அழைப்பைத் துண்டித்து பிளாக் செய்", evt_fraud_b: "OTP-யைப் பகிர்",
        evt_seeds_title: "மோசமான முளைப்பு", evt_seeds_desc: "விதைகள் சரியாக முளைக்கவில்லை.", evt_seeds_a: "மீண்டும் விதைக்க", evt_seeds_b: "காத்திரு",
        evt_monsoon_title: "பருவமழை தாமதம்", evt_monsoon_desc: "மழை தாமதமாகிறது. மண் வறண்டு போகிறது.", evt_monsoon_a: "தண்ணீர் லாரி வாடகைக்கு எடு", evt_monsoon_b: "மழையை நம்பியிரு",
        evt_theft_title: "பண ஆபத்து", evt_theft_desc: "உரத்திற்காக பெருமளவு பணத்தை எடுத்துச் செல்வது ஆபத்தானது.", evt_theft_a: "UPI மூலம் செலுத்து", evt_theft_b: "பணமாக செலுத்து",
        evt_pest_title: "பூச்சி தாக்குதல்", evt_pest_desc: "பூச்சிகள் பயிரை சேதப்படுத்துகின்றன.", evt_pest_a: "பூச்சிக்கொல்லி மருந்து தெளிக்க", evt_pest_b: "வீட்டு வைத்தியம்",
        evt_motor_title: "மோட்டார் எரிந்தது", evt_motor_desc: "அதிக மின்னழுத்தத்தால் மோட்டார் எரிந்தது.", evt_motor_a: "உடனடியாக சரிசெய்", evt_motor_b: "பாசனத்தைத் தவிர்",
        evt_mandi_title: "வியாபாரி vs மண்டி", evt_mandi_desc: "உள்ளூர் வியாபாரி உடனடியாக பணம் தருகிறார், ஆனால் விலை குறைவு.", evt_mandi_a: "மண்டியில் விற்க (UPI)", evt_mandi_b: "வியாபாரியிடம் விற்க",
        evt_hail_title: "ஆலங்கட்டி மழை", evt_hail_desc: "அறுவடைக்கு முன்பு ஆலங்கட்டி மழை!", evt_hail_a: "அவசர அறுவடை", evt_hail_b: "எதுவும் செய்ய வேண்டாம்",
        evt_crash_title: "விலை வீழ்ச்சி", evt_crash_desc: "சந்தை விலை 40% குறைந்தது.", evt_crash_a: "குளிர்பதன கிடங்கை பயன்படுத்து", evt_crash_b: "குறைந்த விலைக்கு விற்க",
        sum_complete: "சிமுலேஷன் முடிந்தது", sum_identity: "உங்கள் நிதி அடையாளம்", sum_report: "இறுதி அறிக்கை", sum_networth: "மொத்த சொத்து மதிப்பு", sum_land: "சொந்த நிலம்", sum_goals: "இலக்குகள் அடையப்பட்டன", sum_final_debt: "இறுதி கடன்", sum_restart: "புதிய பயணத்தை தொடங்கு",
        per_debt_t: "கடன் பெற்றவர்", per_debt_d: "நீங்கள் உயிர் பிழைத்தீர்கள், ஆனால் ₹{val} கடனில். அதிக வட்டி கடன்கள் உங்கள் எதிர்காலத்தை அழித்துவிட்டன.", per_ratna_t: "கிருஷி ரத்னா", per_ratna_d: "விவசாயத்தில் மாஸ்டர்! நீங்கள் உங்கள் கனவை அடைந்து பெரும் சொத்தை உருவாக்கியுள்ளீர்கள்.", per_dream_t: "கனவை அடைந்தவர்", per_dream_d: "வாழ்த்துக்கள்! நீங்கள் உங்கள் கனவை அடைந்துவிட்டீர்கள்: {val}. நீங்கள் நிதி சுதந்திரம் பெற்றுள்ளீர்கள்.", per_zamin_t: "ஜமீன்தார்", per_zamin_d: "உங்கள் பண்ணையை {val} ஏக்கராக விரிவுபடுத்தியுள்ளீர்கள்! நீங்களே மிகப்பெரிய நில உரிமையாளர்.", per_invest_t: "புத்திசாலி முதலீட்டாளர்", per_invest_d: "நீங்கள் வங்கியின் மூலம் பெரும் செல்வத்தை சேர்த்தீர்கள், ஆனால் முக்கிய இலக்கை மறந்துவிட்டீர்கள்.", per_bank_t: "வங்கியின் விருப்பம்", per_bank_d: "உங்கள் கடன் மதிப்பெண் (800+) சிறப்பாக உள்ளது. அடுத்த முறை கொஞ்சம் ஆபத்து எடுங்கள்.", per_survive_t: "உயிர் பிழைத்தவர்", per_survive_d: "நீங்கள் {val} பருவங்களை முடித்துவிட்டீர்கள். கஷ்டங்களை சந்தித்தீர்கள்.",
        adv_urgent_debt: "⚠️ அவசரம்: உங்கள் கடன் மிக அதிகமாக உள்ளது. கடனை அடைக்கவும்!", adv_poverty_spiral: "🚨 எச்சரிக்கை: நீங்கள் கடன் வலையில் உள்ளீர்கள்! வங்கி கடனை நாடுங்கள்.", adv_use_score: "💡 4% KCC கடனுக்கு முன்னுரிமை கொடுங்கள்.", adv_pm_kisan: "💡 குறிப்பு: ₹2,000 PM-KISAN பெற அரசு திட்டங்களை பார்க்கவும்.", adv_fd_idle: "📈 குறிப்பு: உங்களிடம் ₹{val} சும்மா உள்ளது. FD-யில் முதலீடு செய்யவும்!", adv_soil_health: "🌱 குறிப்பு: உரச் செலவைக் குறைக்க மண் வள அட்டை பெறவும்.", adv_pmfby: "🛡️ குறிப்பு: 50% மானியம் பெற PMFBY-ல் சேரவும்.", adv_improve_credit: "🏦 குறிப்பு: கடன் மதிப்பெண்ணை மேம்படுத்த கடனை அடைக்கவும்.", adv_solar_kusum: "☀️ குறிப்பு: சூரிய பம்ப் மானியம் பெற PM-KUSUM க்கு விண்ணப்பிக்கவும்!", adv_expand_land: "🚜 குறிப்பு: புதிய நிலம் வாங்க உங்களிடம் பணம் உள்ளது.", adv_buy_gold: "🪙 குறிப்பு: டிஜிட்டல் தங்கம் வாங்கவும்.", adv_gen_moneylender: "36% வட்டி உங்களை கடன் வலையில் தள்ளும்.", adv_gen_diversify: "பயிர் பன்முகத்தன்மை வானிலையிலிருந்து பாதுகாக்கும்.", adv_gen_drip: "சொட்டு நீர் பாசனம் வறட்சி பாதிப்பை குறைக்கிறது.", adv_gen_transport: "விற்பதற்கு முன் போக்குவரத்து செலவை சரிபார்க்கவும்.", adv_gen_praise: "🌟 மிகச் சிறப்பு! உங்கள் பண்ணை லாபகரமாக உள்ளது.",
        quiz_kcc_q: "கிசான் கிரெடிட் கார்டின் (KCC) முக்கிய நன்மை என்ன?", quiz_kcc_o1: "இலவச டிராக்டர்", quiz_kcc_o2: "குறைந்த வட்டி விவசாய கடன்கள்", quiz_kcc_o3: "வானிலை புதுப்பிப்புகள்", quiz_kcc_o4: "உத்தரவாத சந்தை விலை", quiz_kcc_exp: "KCC விவசாயிகளுக்கு 7% குறைந்த வட்டி விகிதத்தில் கடன்களை வழங்குகிறது.",
        quiz_pmfby_q: "PMFBY திட்டம் உங்களை எதிலிருந்து பாதுகாக்கிறது?", quiz_pmfby_o1: "திருட்டு", quiz_pmfby_o2: "இயற்கை பேரழிவுகளால் ஏற்படும் பயிர் இழப்பு", quiz_pmfby_o3: "மருத்துவ செலவுகள்", quiz_pmfby_o4: "சந்தை விலை வீழ்ச்சி", quiz_pmfby_exp: "வானிலை அல்லது பூச்சிகளால் பயிர்கள் அழிந்தால் விவசாயிகளுக்கு PMFBY காப்பீடு வழங்குகிறது.",
        quiz_compound_q: "கந்து வட்டிக்காரரின் 36% வட்டி ஏன் ஆபத்தானது?", quiz_compound_o1: "காகித வேலைகள்", quiz_compound_o2: "கடன் வேகமாக வளரும் (கடன் பொறி)", quiz_compound_o3: "ரொக்கம் மட்டுமே", quiz_compound_o4: "வங்கிக்கு வித்தியாசம் இல்லை", quiz_compound_exp: "அதிக வட்டி கடன்கள் வேகமாக வளரும். 36% வட்டி விவசாயிகளை நிரந்தர கடன் வலையில் சிக்க வைக்கிறது.",
        quiz_div_q: "'பயிர் பன்முகத்தன்மை' (Crop Diversification) என்றால் என்ன?", quiz_div_o1: "ஒரே பயிர் நடுதல்", quiz_div_o2: "ஆபத்தை குறைக்க வெவ்வேறு பயிர்களை வளர்ப்பது", quiz_div_o3: "வெவ்வேறு சந்தைகளில் விற்பது", quiz_div_o4: "ரசாயன உரங்கள்", quiz_div_exp: "வெவ்வேறு பயிர்களை வளர்ப்பது, ஒரு பயிர் அழிந்தாலும் மற்றொரு பயிர் உயிர்வாழ உதவும்.",
        quiz_inf_q: "உங்கள் சேமிப்பை வீட்டில் ரொக்கமாக வைப்பது ஏன் மோசமானது?", quiz_inf_o1: "பணவீக்கத்தால் பணத்தின் மதிப்பு குறையும்", quiz_inf_o2: "வங்கி கட்டணம் வசூலிக்கும்", quiz_inf_o3: "விதை வாங்க முடியாது", quiz_inf_o4: "துரதிர்ஷ்டம்", quiz_inf_exp: "பணவீக்கம் என்பது காலப்போக்கில் பொருட்கள் விலை உயர்வதாகும். FD-யில் பணத்தை சேமித்தால் அது வளரும்."
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, values?: Record<string, string | number>) => string; 
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('krishiniti_lang') as Language;
        if (savedLang && (translations as any)[savedLang]) {
            setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('krishiniti_lang', lang);
    };

    const t = (key: string, values?: Record<string, string | number>): string => {
        let str = (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
        
        if (values && typeof str === 'string') {
            Object.keys(values).forEach(v => {
                str = str.replace(new RegExp(`{${v}}`, 'g'), values[v].toString());
            });
        }
        return str;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
};